### ISSUE TITLE
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

### ISSUE THREAD

**Issue by jiaohuix** [Ledzy/BAdam#2]
我在修改了一个训练脚本后报错没有梯度，下面是我修改的代码：
```python

    trainer = Seq2SeqTrainer(
        model=model,
        args=training_args,
        train_dataset=train_dataset_merge if training_args.do_train else None,
        eval_dataset=eval_dataset_merge if training_args.do_eval else None,
        tokenizer=tokenizer,
        data_collator=data_collator,
        compute_metrics=compute_metrics if training_args.predict_with_generate else None,
        # optimizers = (optimizer, None)
    )

    if model_args.use_badam:
        try:
            from badam import BlockOptimizer
        except ImportError:
            # raise ImportError("Unable to import badam module. Please install badam or disable its usage.")
            logger.info("Unable to import badam module. Please install badam or disable its usage.")

        # Optimizer
        trainer.create_optimizer_and_scheduler(num_training_steps=training_args.max_steps)
        original_optimizer = trainer.optimizer

        # before training, add this line to wrap the original optimizer
        trainer.optimizer = BlockOptimizer(
            base_optimizer=original_optimizer,  # can be any torch.Optimizer
            named_parameters_list=list(model.named_parameters()),
            switch_block_every=100,
            # switch to the new block every 50 updates, the $K$ Adam steps in paper. It can be set adaptively by $K = n/(BD)$, where $n$ is the number of training data points, $B$ is the batch size, and $D$ is the number of blocks in BAdam; see "Hyperparameter Suggestion" section for a detailed explaination about setting this hyperparameter.
            switch_mode="random",
            # update order of blocks, one can choose "random" (random reshuffling update order), "ascending" (update from input layer to output layer), or "descending" (update from output layer to input layer). The default is "random".
            verbose=2,  # information level, will print trainable parameters when setting to 2
            block_prefix_list = None
        )




```
报错信息如下，有大佬知道怎么解决嘛，蟹蟹~~~

Traceback (most recent call last):
  File "/hy-tmp/mnmt/m2m/scripts/run_translation_fast.py", line 700, in <module>
    main()
  File "/hy-tmp/mnmt/m2m/scripts/run_translation_fast.py", line 616, in main
    train_result = trainer.train(resume_from_checkpoint=checkpoint)
  File "/usr/local/miniconda3/envs/nmt/lib/python3.10/site-packages/transformers/trainer.py", line 1859, in train
    return inner_training_loop(
  File "/usr/local/miniconda3/envs/nmt/lib/python3.10/site-packages/transformers/trainer.py", line 2203, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/usr/local/miniconda3/envs/nmt/lib/python3.10/site-packages/transformers/trainer.py", line 3147, in training_step
    self.accelerator.backward(loss)
  File "/usr/local/miniconda3/envs/nmt/lib/python3.10/site-packages/accelerate/accelerator.py", line 2011, in backward
    self.scaler.scale(loss).backward(**kwargs)
  File "/usr/local/miniconda3/envs/nmt/lib/python3.10/site-packages/torch/_tensor.py", line 522, in backward
    torch.autograd.backward(
  File "/usr/local/miniconda3/envs/nmt/lib/python3.10/site-packages/torch/autograd/__init__.py", line 266, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

**Comment by Ledzy** [comment]
This is due to the Pytorch `checkpoint` function only trains the checkpointed layer when the input's `requires_grad=True`. You need to adjust the behavior of the model's checkpointing function:

```python
from types import MethodType
model.gradient_checkpointing_enable = MethodType(gradient_checkpointing_enable, model)
```

The `gradient_checkpointing_enable` is defined as

```python
def gradient_checkpointing_enable(
    self: "PreTrainedModel", gradient_checkpointing_kwargs: Optional[Dict[str, Any]] = None
) -> None:
    r"""
    Activates gradient checkpointing for the current model.

    Modification of the original method to enable gradient checkpointing for block-wise optimizer.
    """
    from torch.utils.checkpoint import checkpoint

    if not self.supports_gradient_checkpointing:
        raise ValueError("{} does not support gradient checkpointing.".format(self.__class__.__name__))

    if gradient_checkpointing_kwargs is None:
        gradient_checkpointing_kwargs = {"use_reentrant": True}

    gradient_checkpointing_func = partial(checkpoint, **gradient_checkpointing_kwargs)

    def custom_gradient_checkpointing_func(func, *args, **kwargs):
        module: "torch.nn.Module" = func.__self__

        if any(param.requires_grad for param in module.parameters()):
            for arg in args:
                if torch.is_tensor(arg) and torch.is_floating_point(arg):
                    arg.requires_grad_(True)

        return gradient_checkpointing_func(func, *args, **kwargs)

    if "value" in inspect.signature(self._set_gradient_checkpointing).parameters:  # old GC format
        self.apply(partial(self._set_gradient_checkpointing, value=True))
        self.enable_input_require_grads()
        logger.warning("You are using the old GC format, some features (e.g. BAdam) will be invalid.")
    else:  # have already enabled input require gradients
        self._set_gradient_checkpointing(enable=True, gradient_checkpointing_func=custom_gradient_checkpointing_func)
```

You may refer to Llama Factory's implementation: 
* https://github.com/hiyouga/LLaMA-Factory/blob/2efd9b6ba0e06f62d8dc48bc3c4100c829d6795b/src/llmtuner/model/utils.py#L105

**Comment by jiaohuix** [comment]
@Ledzy 大佬，我按照llama-factory里面的改了，还是报相同的错误。我虽然跑通了llama-factory的badam，并且在删除这行后复现了“RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn”错误：
```python

model.gradient_checkpointing_enable = MethodType(_gradient_checkpointing_enable, model)
```

但我在迁移到[run_translation](https://github.com/huggingface/transformers/blob/main/examples/pytorch/translation/run_translation.py)时候还是报了相同的错误 ，这是什么原因呢。会不会是不支持seq2eq的模型额：
```python

def _create_badam_optimizer(
        model: "PreTrainedModel",
        training_args: "BAdamSeq2SeqTrainingArguments",
) -> "torch.optim.Optimizer":
    decay_params, nodecay_params = [], []
    decay_param_names = _get_decay_parameter_names(model)
    for name, param in model.named_parameters():
        if param.requires_grad:
            if name in decay_param_names:
                decay_params.append(param)
            else:
                nodecay_params.append(param)

    optim_class, optim_kwargs = Trainer.get_optimizer_cls_and_kwargs(training_args)
    param_groups = [
        dict(params=nodecay_params, weight_decay=0.0),
        dict(params=decay_params, weight_decay=training_args.weight_decay),
    ]

    if training_args.badam_mode == "layer":
        from badam import BlockOptimizer

        base_optimizer = optim_class(param_groups, **optim_kwargs)
        optimizer = BlockOptimizer(
            base_optimizer=base_optimizer,
            named_parameters_list=list(model.named_parameters()),
            block_prefix_list=None,
            switch_block_every=training_args.badam_switch_block_every,
            start_block=training_args.badam_start_block,
            switch_mode=training_args.badam_switch_mode,
            verbose=training_args.badam_verbose,
        )
        logger.info(
            f"Using BAdam optimizer with layer-wise update, switch mode is {training_args.badam_switch_mode}, "
            f"switch block every {training_args.badam_switch_block_every} steps, "
            f"default start block is {training_args.badam_start_block}"
        )

    elif training_args.badam_mode == "ratio":
        from badam import BlockOptimizerRatio

        assert training_args.badam_update_ratio > 1e-6
        optimizer = BlockOptimizerRatio(
            param_groups=param_groups,
            named_parameters_list=list(model.named_parameters()),
            update_ratio=training_args.badam_update_ratio,
            mask_mode=training_args.badam_mask_mode,
            verbose=training_args.badam_verbose,
            include_embedding=False,
            **optim_kwargs,
        )
        logger.info(
            f"Using BAdam optimizer with ratio-wise update, update ratio is {training_args.badam_update_ratio}, "
            f"mask mode is {training_args.badam_mask_mode}"
        )

    return optimizer


class CustomSeq2SeqTrainer(Seq2SeqTrainer):
    r"""
    Inherits Seq2SeqTrainer to use BAdam optimizer.
    """

    def __init__(self, **kwargs) -> None:
        super().__init__(**kwargs)
        print("type args:", type(self.args), self.args)

        if self.args.use_badam:
            from badam import clip_grad_norm_for_sparse_tensor

            self.accelerator.clip_grad_norm_ = MethodType(clip_grad_norm_for_sparse_tensor, self.accelerator)

    def create_optimizer(self) -> "torch.optim.Optimizer":
        if self.optimizer is None and self.args.use_badam:
            self.optimizer = _create_badam_optimizer(self.model, self.args)
        else:
        return super().create_optimizer()


def _gradient_checkpointing_enable(
        self: "PreTrainedModel", gradient_checkpointing_kwargs: Optional[Dict[str, Any]] = None
) -> None:
    r"""
    Activates gradient checkpointing for the current model.

    Modification of the original method to enable gradient checkpointing for block-wise optimizer.
    """
    from torch.utils.checkpoint import checkpoint

    if not self.supports_gradient_checkpointing:
        raise ValueError("{} does not support gradient checkpointing.".format(self.__class__.__name__))

    if gradient_checkpointing_kwargs is None:
        gradient_checkpointing_kwargs = {"use_reentrant": True}

    gradient_checkpointing_func = partial(checkpoint, **gradient_checkpointing_kwargs)

    def custom_gradient_checkpointing_func(func, *args, **kwargs):
        module: "torch.nn.Module" = func.__self__

        if any(param.requires_grad for param in module.parameters()):
            for arg in args:
                if torch.is_tensor(arg) and torch.is_floating_point(arg):
                    arg.requires_grad_(True)

        return gradient_checkpointing_func(func, *args, **kwargs)

    if "value" in inspect.signature(self._set_gradient_checkpointing).parameters:  # old GC format
        self.apply(partial(self._set_gradient_checkpointing, value=True))
        self.enable_input_require_grads()
        logger.warning("You are using the old GC format, some features (e.g. BAdam) will be invalid.")

    else:  # have already enabled input require gradients
        self._set_gradient_checkpointing(enable=True, gradient_checkpointing_func=custom_gradient_checkpointing_func)



disable_gradient_checkpointing = not training_args.gradient_checkpointing
if not disable_gradient_checkpointing:
    if not getattr(model, "supports_gradient_checkpointing", False):
        logger.warning("Current model does not support gradient checkpointing.")
    else:
        # use_reentrant=False might increase VRAM usage (have not been empirically verified yet)
        # According to: https://github.com/huggingface/transformers/issues/28339
        model.gradient_checkpointing_enable = MethodType(_gradient_checkpointing_enable, model)
        model.gradient_checkpointing_enable(gradient_checkpointing_kwargs={"use_reentrant": True})
        setattr(model.config, "use_cache", False)  # turn off when gradient checkpointing is enabled
        logger.info("Gradient checkpointing enabled.")


trainer = CustomSeq2SeqTrainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset_merge if training_args.do_train else None,
    eval_dataset=eval_dataset_merge if training_args.do_eval else None,
    tokenizer=tokenizer,
    data_collator=data_collator,
    compute_metrics=compute_metrics if training_args.predict_with_generate else None,
)




```

**Comment by Ledzy** [comment]
BAdam is an optimization algorithm which is architecture independent and problem independent, and it should work for `Seq2SeqTrainer`.

You should first check if adding `model.enable_input_require_grads()` will resolve the issue. This set output of embedding layer `requries_grad=True`, and thereby set inputs of all checkpoint layer `requries_grad=True`, so that the gradient of the active block can be succesfully calculated. However, this approach will introduce unnecessary backward cost and approximately double the average backward time; it also increases the memory usage a bit for storing additional activation values.

If the aforementioned approach works, you should check if the modified checkpoint function is successfully invoked and correctly adjust the input's trainability during the forward pass. For instance, you may set a breakpoint at `custom_gradient_checkpointing_func`: When `module` is the trainable block's parameter, its input should be set `requires_grad=True`.

If these approaches still do not work, please let us know. We would appreciate it if more error messages and implementation details can be provided.
